### ISSUE TITLE
stuck on getting data from blockchain

### ISSUE THREAD

**Issue by lord-dubious** [rgalyeon/Linea_Park#2]
heck quests progress from blockchain data
  0%|                                                                                                            | 0/1 [00:00<?, ?it/s]

**Comment by rgalyeon** [comment]
If the progress bar is standing still, then the software cannot get a response to the request from LineaScan. This can happen due to enabled VPN (many people are sitting from the same IP, and the free LineaScan API has a limit on the number of requests).
